### ISSUE TITLE
Constant `bootstrap completed but connectivity has not been reached` error spew on single-node cluster

### ISSUE THREAD

**Issue by brandond** [spegel-org/spegel#1120]
### Spegel version

main

### Kubernetes distribution

n/a

### Kubernetes version

n/a

### CNI

n/a

### Describe the bug

On single-node clusters, spegel continuously logs ERROR-level messages about connectivity problems every few seconds. The errors go away when another node joins the cluster, but this is very irritating.

> ```
> ERRO[0049] failed to run bootstrap                       attempts=17 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0057] failed to run bootstrap                       attempts=18 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0062] failed to run bootstrap                       attempts=19 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0071] failed to run bootstrap                       attempts=20 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0078] failed to run bootstrap                       attempts=21 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0080] failed to run bootstrap                       attempts=22 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0088] failed to run bootstrap                       attempts=23 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0096] failed to run bootstrap                       attempts=24 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0102] failed to run bootstrap                       attempts=25 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0109] failed to run bootstrap                       attempts=26 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0113] failed to run bootstrap                       attempts=27 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0114] failed to run bootstrap                       attempts=28 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0115] failed to run bootstrap                       attempts=29 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0123] failed to run bootstrap                       attempts=30 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0127] failed to run bootstrap                       attempts=31 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0133] failed to run bootstrap                       attempts=32 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0143] failed to run bootstrap                       attempts=33 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0145] failed to run bootstrap                       attempts=34 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
> ERRO[0147] failed to run bootstrap                       attempts=35 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
>``` 

These should probably be debug or perhaps warning at worst. It should not be an error to run Spegel on a single node.

**Comment by phillebaba** [comment]
This bug was fixed in #1110 with an additional check before exiting the retry loop. The bootstrap will backoff to 10 seconds if bootstrap is not possible. Running a single instance of Spegel is seen as it not being ready because it has no peers to route to.

**Comment by brandond** [comment]
This is still an issue. Can we make this configurable or something? I'd prefer not to have to write a log intercepter just to be able to run spegel on cluster that consists of a single node for a period of time without it spamming the logs.

```
I1218 18:02:20.520194      54 shared_informer.go:370] "Waiting for caches to sync"
ERRO[0044] failed to run bootstrap                       attempts=17 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
I1218 18:02:21.620451      54 shared_informer.go:370] "Waiting for caches to sync"
I1218 18:02:21.821242      54 shared_informer.go:377] "Caches are synced"
I1218 18:02:22.720884      54 shared_informer.go:377] "Caches are synced"
ERRO[0052] failed to run bootstrap                       attempts=18 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0056] failed to run bootstrap                       attempts=19 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0066] failed to run bootstrap                       attempts=20 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0075] failed to run bootstrap                       attempts=21 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0079] failed to run bootstrap                       attempts=22 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0085] failed to run bootstrap                       attempts=23 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0087] failed to run bootstrap                       attempts=24 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0095] failed to run bootstrap                       attempts=25 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0100] failed to run bootstrap                       attempts=26 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0101] failed to run bootstrap                       attempts=27 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0105] failed to run bootstrap                       attempts=28 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0108] failed to run bootstrap                       attempts=29 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0112] failed to run bootstrap                       attempts=30 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0117] failed to run bootstrap                       attempts=31 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0121] failed to run bootstrap                       attempts=32 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p
ERRO[0128] failed to run bootstrap                       attempts=33 error="bootstrap completed but connectivity has not been reached" logger=spegel/p2p

```
